apiVersion: v1
kind: Namespace
metadata:
  name: pde-fluid-phi
  labels:
    app: pde-fluid-phi
    version: v0.1.0
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pde-fluid-phi-quota
  namespace: pde-fluid-phi
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    requests.nvidia.com/gpu: "4"
    limits.cpu: "40"
    limits.memory: 80Gi
    limits.nvidia.com/gpu: "4"
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pde-fluid-phi-netpol
  namespace: pde-fluid-phi
spec:
  podSelector:
    matchLabels:
      app: pde-fluid-phi
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: pde-fluid-phi
    - podSelector:
        matchLabels:
          app: pde-fluid-phi
  egress:
  - {}  # Allow all egress for external dependencies