apiVersion: apps/v1
kind: Deployment
metadata:
  name: pde-fluid-phi
  labels:
    app: pde-fluid-phi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pde-fluid-phi
  template:
    metadata:
      labels:
        app: pde-fluid-phi
    spec:
      containers:
      - name: pde-fluid-phi
        image: pde-fluid-phi:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 4
            memory: 8Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pde-fluid-phi-service
spec:
  selector:
    app: pde-fluid-phi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
