name: "Neural Operator CI/CD"
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      -
        uses: "actions/checkout@v3"
      -
        name: "Set up Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"
      -
        name: "Install dependencies"
        run: "pip install -r requirements.txt"
      -
        name: "Run tests"
        run: "python3 comprehensive_test_runner.py"
      -
        name: "Security scan"
        run: "python3 security_quality_gates.py"
  build-and-deploy:
    needs: "test"
    runs-on: "ubuntu-latest"
    if: "github.ref == 'refs/heads/main'"
    steps:
      -
        uses: "actions/checkout@v3"
      -
        name: "Build Docker image"
        run: "docker build -t terragon/pde-fluid-phi:${{ github.sha }} ."
      -
        name: "Push to registry"
        run: "docker push terragon/pde-fluid-phi:${{ github.sha }}"
